### ISSUE TITLE
Borgs cannot make windoors whithout human intervention

### ISSUE THREAD

**Issue by Ludox235** [yogstation13/Yogstation-TG#3030]
[Round ID]: # 19104

[Reproduction]: 1. Be engiborg
2. Make windoor frame
3. Proceed to construct the windoor frame until you are at the "insert airlock electronic" one
4. You cannot use the electroadaptive pseudocircuit to use as a airlock electronic (You only just smash it on the windoor)

**Comment by Firewolf34** [comment]
It appears that Borgs cannot make doors _AT ALL_ using the electroadaptive pseudocircuit. It doesn't create airlock circuitry of any type. 

In fact, there's no mention of airlocks whatsoever in any of the code/descriptions for the electroadaptive pseudocircuit. It doesn't seem like it was intended to create airlock circuitry. It can't even recycle them.

Not sure if this is ideal or not, since Borgs can already create airlocks with the RCD. I suppose getting it to create airlock circuitry might be a tad bit more difficult because airlock circuitry can be configured by using it. The borg would have no way to do this since it cannot hold the circuit. 

Otherwise I'd patch this right in. What do you guy think about this?
